name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sbacr02.azurecr.io/alun01:latest

    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: sbacr02 
        # Container registry password
        password: ${{secrets.ACR_PASSWORD}} 
        # Container registry server url
        login-server: sbacr02.azurecr.io
    - name: ACR Push image
      run: docker push sbacr02.azurecr.io/alun01:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    - uses: actions/checkout@v2 
    
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{secrets.KUBECONFIG}} # Does this take the whole file? Wow.
      id: login
      
    - name: Kubernetes Deployment
      run: kubectl apply -f deployment.yaml
    - name: Service Deployment
      run: kubectl apply -f service.yaml
    
